### ISSUE TITLE
Objective-C can't change controlMethod

### ISSUE THREAD

**Issue by AlanFloyd** [scihant/CTPanoramaView#11]
Great work done! I am able to use it in my Objective-C project, except for the controlMethod. I can't get this property into he code. Always giving a compile error - CTPanoramaView doesn't has a property controlMethod.

**Comment by scihant** [comment]
Thanks for reporting this. That property was declared in a way that was preventing it from being available to Obj-C. I fixed it now in the development branch. You can use it until I make a new release when Swift 4 comes out.
