### ISSUE TITLE
controlMethod in Objective-C not available

### ISSUE THREAD

**Issue by tex4ever** [scihant/CTPanoramaView#13]
I use this over Pods in my Objective-C project. For any reasons the property "controlMethod" is not available for Objective-C, but panoramaType is available. Why?
When I add the property controlMethod manually to the Objective-C wrapper then it works, but it will be removed on next clean/build of course, how to fix it permanent?

// Generated by Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
...
@property (nonatomic) enum CTPanoramaType panoramaType;
//controlMethod manually added
@property (nonatomic) enum CTPanoramaControlMethod controlMethod;

Thanks
Philipp

**Comment by scihant** [comment]
This issue has already been resolved in #11 . I'm waiting for XCode 9 and Swift 4 to be officially released before drafting a new release. For now, you can use the development branch, which contains the aforementioned fix.
