### ISSUE TITLE
Instance member yFov in CTPanoramaView

### ISSUE THREAD

**Issue by carguti** [scihant/CTPanoramaView#16]
There is a compilation error in the lazy property fovHeight in CTPanoramaView.swift (line 81)

private lazy var fovHeight: CGFloat = {
        return tan(yFov/2 * .pi / 180.0) * 2 * self.radius <- Error: Instance member 'yFov' cannot be used on type 'CTPanoramaView'
    }()

Due to it is a lazy var, the properties must be accessed with "self" prefix

![screenshot_errorctpanoramaview](https://user-images.githubusercontent.com/23277651/31074762-7a004ff6-a772-11e7-96b0-b081ebdbcfa3.png)

Thank you

**Comment by scihant** [comment]
Thank you for reporting the issue. It's weird that TravisCI didn't report it. Fixed in the 1.1 release
