### ISSUE TITLE
XCode 10.2 Build Error Swift 3 unsupported

### ISSUE THREAD

**Issue by BradPatras** [scihant/CTPanoramaView#38]
After updating to XCode 10.2 a project using CTPanoramaView via cocoapods fails build with this error:

> SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'CTPanoramaView')

<img width="607" alt="Screen Shot 2019-04-05 at 2 35 01 PM" src="https://user-images.githubusercontent.com/7176921/55652061-1209bf00-57b0-11e9-82a3-9352e74fb501.png">

**Comment by scihant** [comment]
Fixed.
