### ISSUE TITLE
Add support for a max-zoom level

### ISSUE THREAD

**Issue by bitwizardry-net** [scihant/CTPanoramaView#39]
Currently the pinch-to-zoom  level is fixed between 20 and 80. Depending on your picture quality the max zoom level can be too high which will result in blurry/pixelated pictures. It would be great to have an option to configure this.

**Comment by scihant** [comment]
Added two variables (minFoV and maxFoV) in 6e2264c1937bbdc6452026a5e5d75a78de6e2b8c. It's available in the latest release.
