### ISSUE TITLE
Specify a Swift version for Cocoapods

### ISSUE THREAD

**Issue by lchamp** [scihant/CTPanoramaView#40]
With cocoapods version 1.6.1 I get the following error:

> [!] Unable to determine Swift version for the following pods:
> - `CTPanoramaView` does not specify a Swift version and none of the targets (_targetlist_) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

Could you please add the "swift version" in the pod declaration?

**Comment by lchamp** [comment]
cc @scihant

**Comment by scihant** [comment]
Done with the latest release
