### ISSUE TITLE
Allow both motion and finger rotation?

### ISSUE THREAD

**Issue by cristianoccazinsp** [scihant/CTPanoramaView#46]
Is it possible to have both rotation methods?

Or perhaps, an "auto" mode that changes from finger to motion if certain movement is detected?

**Comment by ghass64** [comment]
@cristianoccazinsp good job 
is this pull request included in the library or not yet ?
am waiting for it

**Comment by cristianoccazinsp** [comment]
I don't think it has been merged yet. In fact, it was closed without merging, so my guess is that the library owner doesn't want the change at all.  We have been thinking about vendoring this library into the parent library (https://github.com/lightbasenl/react-native-panorama-view which also hasn't finished the changes yet), but haven't had time to do that yet.

**Comment by PeHk** [comment]
Hi @cristianoccazinsp, I've used your solution for handling both, gestures and motion and it works quite nice! Thank you for such a contribution. May I ask you, maybe you can help me a lot, did you know how to set `startAngle` - the offset for panorama even when we talking about spherical one? In your solution, there is no starting angle used when we talking about spherical panorama. It would be very nice if you can share your thoughts! Thanks!

**Comment by cristianoccazinsp** [comment]
I believe there was a hardcoded initial value somewhere in the code. I haven’t worked on that for a long one so I’m not sure. We’ve also ended up censoring this library into a react native project so it is also a bit outdated.

**Comment by scihant** [comment]
Hey @cristianoccazinsp, sorry for the extremely late response. I wasn't really be able to spend time on this lib for the last year.

I can see that you still have a PR waiting to be merged: https://github.com/scihant/CTPanoramaView/pull/54

I'll update the project for XCode 13 next week, and also check if that PR works correctly (it doesn't have any conflicts so it should be fine) and then merge it before creating a new release.

**Comment by PeHk** [comment]
> Hey @cristianoccazinsp, sorry for the extremely late response. I wasn't really be able to spend time on this lib for the last year.
> 
> I can see that you still have a PR waiting to be merged: #54
> 
> I'll update the project for XCode 13 next week, and also check if that PR works correctly (it doesn't have any conflicts so it should be fine) and then merge it before creating a new release.

What a great news! Do you plan to add a offset / compass calibration to the new version as well?

**Comment by cristianoccazinsp** [comment]
@PeHk im not currently working on it, but you may see the related work in this library, perhaps the maintainer is willing to work on it: 

https://github.com/lightbasenl/react-native-panorama-view

**Comment by scihant** [comment]
@PeHk  I had developed this lib because I needed it for one of my projects and there was none available. So I open sourced it so that other people can make use of it too, but I don't really do much about it anymore other than occasionally updating it with each new release of iOS and merging PRs.

**Comment by scihant** [comment]
Now that the PR is merged, I'm closing this issue.
