### ISSUE TITLE
Angle is reset when setting an image

### ISSUE THREAD

**Issue by hardeverick** [scihant/CTPanoramaView#49]
When using touch and you set a new image the angle is reset to 0.

I'm trying to play an MJPEG stream of 360 photos and this keeps resetting the angle.
You should consider making the reset optional

**Comment by scihant** [comment]
Fixed this issue by removing the calls to the reset method and making it public so that it can be called from outside when needed.
6e2264c1937bbdc6452026a5e5d75a78de6e2b8c
