### ISSUE TITLE
Xcode Compilation Errors for UIImage Property

### ISSUE THREAD

**Issue by vadymus** [scihant/CTPanoramaView#52]
When I add `CTPanoramaView.swift` to Xcode 12.0 beta 6 or Xcode 11.x I am getting 2 compilation errors:

1. Overriding non-open property outside of its defining module
2. Property 'image' with type 'UIImage?' cannot override a property with type 'UIImage'

in this code

```
    @objc public var image: UIImage? {
        didSet {
            panoramaType = panoramaTypeForCurrentImage
        }
    }
```

Any ideas why this is happening? Would like to try this library.

**Comment by scihant** [comment]
It seems like you're trying to override a public property, which is not possible. Even if it was, you couldn't convert an optional property to a non-optional one while doing so.
