### ISSUE TITLE
Why does deployment target is iOS 12 now?

### ISSUE THREAD

**Issue by Sega-Zero** [scihant/CTPanoramaView#56]
The readme file declares iOS 8.0+, but podspec requires iOS12. 
Where is the mistake?

**Comment by scihant** [comment]
Yes, it seems like I forgot to update it. The podspec is correct. iOS 8.0 is way too old.

**Comment by Sega-Zero** [comment]
Yep, but there is nothing in the code that should drop iOS 8 support?
I use your library on iOS 9+ project and everything is working fine ¯\_(ツ)_/¯

**Comment by scihant** [comment]
That might be true :) iOS 12 isn't really necessary but if I remember correctly, Xcode 12 doesn't really support iOS 8.0. Don't know about 9.0 though. I could reduce it to the minimum iOS version latest XCode supports (which certainly is lower than 12)

**Comment by Sega-Zero** [comment]
Supporting iOS8 project in XCode12 without any troubles :)

**Comment by scihant** [comment]
I've just checked. It doesn't list 8.0 as an option out of the box.

But you're right about the rest. I don't really remember why I bumped the version to 12. I even have some availability checks for iOS 11 in code, so it must be a mistake :)

I'll fix this when I'm able.

**Comment by Sega-Zero** [comment]
Thanks!

**Comment by scihant** [comment]
It's 10.0 now.
