### ISSUE TITLE
I am Getting error message in Xcode 12 14.4 

### ISSUE THREAD

**Issue by QDWorld** [scihant/CTPanoramaView#59]
switch UIApplication.shared.statusBarOrientation
<img width="1027" alt="Screenshot 2021-06-02 at 10 52 19 PM" src="https://user-images.githubusercontent.com/54508332/120524964-4069a000-c3f5-11eb-918f-6560a8ee1f52.png">

**Comment by scihant** [comment]
That was because the libraries deploment target was set to 12 unnecessarily.
